# Generated by Django 3.1.7 on 2021-03-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.CharField(max_length=200),
        ),
    ]
